import {
  BadRequestException,
  Body,
  Controller,
  Get,
  Header,
  NotFoundException,
  Param,
  Post,
  Query,
  UseGuards,
} from '@nestjs/common';
import { AuthGuard, CurrentUser } from '../phase2/auth.guard';
import { Roles, RolesGuard } from '../phase2/roles.guard';
import { Phase4Service } from './phase4.service';

@Controller()
export class Phase4Controller {
  constructor(private readonly phase4: Phase4Service) {}

  @Get('tourism')
  @Header('Cache-Control', 'public, max-age=300')
  tourismIndex() {
    return this.phase4.tourismIndex();
  }

  @Get('tourism/:slug')
  @Header('Cache-Control', 'public, max-age=300')
  tourismStructure(@Param('slug') slug: string) {
    const row = this.phase4.tourismStructure(slug);
    if (!row) throw new NotFoundException('Structure not found');
    return row;
  }

  @Get('construction/window')
  @Header('Cache-Control', 'public, max-age=120')
  constructionWindow(
    @Query('month') month?: string,
    @Query('year') year?: string,
    @Query('projectType') projectType?: string,
  ) {
    return this.phase4.constructionWindow({
      targetBuildMonth: month ? Number(month) : undefined,
      targetBuildYear: year ? Number(year) : undefined,
      projectType: projectType?.toUpperCase(),
    });
  }

  @Get('construction/ships')
  @Header('Cache-Control', 'public, max-age=300')
  ships(@Query('year') year?: string, @Query('month') month?: string) {
    const y = year ? Number(year) : new Date().getUTCFullYear();
    return this.phase4.shipCalendar(y, month ? Number(month) : undefined);
  }

  @Get('meetings/:id/summary')
  @Header('Cache-Control', 'public, max-age=120')
  publicSummary(@Param('id') id: string) {
    const s = this.phase4.publishedSummaryForMeeting(id);
    if (!s) {
      return {
        published: false,
        summary: null,
        note: 'No human-reviewed summary is published for this meeting. Unreviewed AI drafts are never shown here.',
      };
    }
    return {
      published: true,
      generatedByAi: true,
      humanReviewed: true,
      summary: s,
    };
  }

  @Get('summaries')
  @Header('Cache-Control', 'public, max-age=120')
  listPublished() {
    return {
      generatedByAiLabel: 'Generated by AI — verify against primary minutes/video.',
      summaries: this.phase4.listPublishedSummaries(),
    };
  }

  @Get('summaries/moderation')
  @UseGuards(AuthGuard, RolesGuard)
  @Roles('STAFF', 'ADMIN')
  moderationQueue(@CurrentUser() _user: { email: string }) {
    return {
      summaries: this.phase4.listAllSummariesForStaff(),
      rule: 'Do not publish unreviewed summaries.',
    };
  }

  @Post('summaries/:id/review')
  @UseGuards(AuthGuard, RolesGuard)
  @Roles('STAFF', 'ADMIN')
  review(
    @CurrentUser() user: { email: string },
    @Param('id') id: string,
    @Body() body: { publish?: boolean },
  ) {
    if (body.publish == null) throw new BadRequestException('publish boolean required');
    const row = this.phase4.reviewSummary(id, user.email, body.publish);
    if (!row) throw new NotFoundException('Summary not found');
    return { summary: row };
  }
}
