import { Injectable } from '@nestjs/common';
import PDFDocument from 'pdfkit';

export type PackageInput = {
  applicantName: string;
  projectType: string;
  description: string;
  parcelLabel: string;
  structureLabel: string;
  triageOutcome: string | null;
  criteria: string[];
  exhibitsRequired: string[];
  documents: { kind: string; fileName: string }[];
  agencyNotes: string[];
  codeCites: string[];
};

@Injectable()
export class PdfService {
  async buildSubmittalPackage(input: PackageInput): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 54, size: 'LETTER' });
      const chunks: Buffer[] = [];
      doc.on('data', (c) => chunks.push(c as Buffer));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      doc.fontSize(18).text('Creek Street HD — Pre-application package', { align: 'left' });
      doc.moveDown(0.3);
      doc
        .fontSize(9)
        .fillColor('#444444')
        .text(
          'PREPARATION TOOL ONLY. Official submission is to the Ketchikan Gateway Borough Planning Department. This PDF is not a filing and is not a borough record.',
        );
      doc.fillColor('#000000');
      doc.moveDown();

      doc.fontSize(12).text(`Applicant: ${input.applicantName || '—'}`);
      doc.text(`Project type: ${input.projectType.replace(/_/g, ' ')}`);
      doc.text(`Parcel: ${input.parcelLabel}`);
      doc.text(`Structure: ${input.structureLabel}`);
      if (input.triageOutcome) doc.text(`Triage outcome (informational): ${input.triageOutcome}`);
      doc.moveDown();

      doc.fontSize(13).text('Project description');
      doc.fontSize(11).text(input.description || '(none provided)', { align: 'left' });
      doc.moveDown();

      doc.fontSize(13).text('Applicable criteria (from triage / guidance)');
      if (input.criteria.length === 0) doc.fontSize(11).text('—');
      else input.criteria.forEach((c) => doc.fontSize(11).text(`• ${c.replace(/_/g, ' ')}`));
      doc.moveDown();

      doc.fontSize(13).text('Code cites referenced');
      input.codeCites.forEach((c) => doc.fontSize(11).text(`• ${c}`));
      doc.moveDown();

      doc.fontSize(13).text('Exhibit checklist');
      input.exhibitsRequired.forEach((k) => {
        const uploaded = input.documents.find((d) => d.kind === k);
        doc.fontSize(11).text(`• ${k}${uploaded ? ` — attached as ${uploaded.fileName}` : ' — MISSING'}`);
      });
      doc.moveDown();

      if (input.agencyNotes.length) {
        doc.fontSize(13).text('Possible multi-agency triggers (verify independently)');
        input.agencyNotes.forEach((n) => doc.fontSize(11).text(`• ${n}`));
        doc.moveDown();
      }

      doc
        .fontSize(9)
        .fillColor('#444444')
        .text(
          'Generated by Creek Street Design Review Hub (Mitchel Turner Dev, LLC) — not a borough property. Confirm requirements with the Zoning Administrator before filing.',
        );

      doc.end();
    });
  }
}
