import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { PageHeader } from '../components/PageHeader';
import { SourceLink } from '../components/SourceLink';
import { statusLabel } from '../lib/api';

type SummarySheet = {
  phase: number;
  generatedByAi: boolean;
  humanReviewed: boolean;
  meeting: {
    id: string;
    scheduledAt: string;
    location: string;
    status: string;
    minutesUrl: string | null;
    videoUrl: string | null;
  };
  summary: {
    id: string;
    body: string;
    model: string;
    reviewedBy: string | null;
    reviewedAt: string | null;
  };
  items: Array<{
    agendaItem: { id: string; itemNumber: string; title: string };
    application: {
      id: string;
      caseNumber: string | null;
      projectType: string;
      status: string;
      caseBriefUi: string;
    } | null;
    structure: {
      commonName: string | null;
      addressLabel: string;
      publicSlug: string;
    } | null;
    itemSummary: { text: string; sourceRefs: string[] } | null;
    note: string | null;
  }>;
  links: {
    agendaUi: string;
    outcomesUi: string | null;
    packetPdf: string;
  };
  disclaimer: string;
};

export function MeetingSummaryPage() {
  const { id = '' } = useParams();
  const [data, setData] = useState<SummarySheet | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!id) return;
    fetch(`/api/meetings/${id}/summary-sheet`)
      .then(async (r) => {
        if (!r.ok) throw new Error(await r.text());
        return r.json() as Promise<SummarySheet>;
      })
      .then(setData)
      .catch((e: Error) => setError(e.message));
  }, [id]);

  return (
    <div className="mx-auto max-w-4xl px-4 py-10 md:px-6">
      <PageHeader
        title="Meeting summary"
        lede="AI-generated summary published after human review. Verify against Clerk minutes and video."
      />

      <p className="mb-6 flex flex-wrap gap-4 text-sm">
        <Link to="/meetings" className="font-semibold text-creek underline">
          ← Meeting calendar
        </Link>
        <Link to={`/meetings/${id}`} className="font-semibold text-creek underline">
          Agenda brief
        </Link>
      </p>

      {error ? <p className="mb-4 text-sm text-red-700">{error}</p> : null}
      {!data && !error ? <p className="text-sm text-ink/50">Loading summary…</p> : null}

      {data ? (
        <div className="space-y-8">
          <p className="border-l-2 border-brass/70 pl-3 text-sm text-ink/70">{data.disclaimer}</p>

          <section className="space-y-2">
            <h2 className="font-display text-2xl text-ink">Meeting</h2>
            <p className="text-sm text-ink/75">
              {new Date(data.meeting.scheduledAt).toLocaleString('en-US', {
                timeZone: 'America/Juneau',
              })}{' '}
              · {data.meeting.location}
            </p>
            <p className="text-sm text-ink/55">
              {data.meeting.status.replace(/_/g, ' ')} · reviewed by{' '}
              {data.summary.reviewedBy ?? 'staff'}
              {data.summary.reviewedAt
                ? ` · ${new Date(data.summary.reviewedAt).toLocaleDateString()}`
                : ''}
            </p>
            <div className="flex flex-wrap gap-4 pt-1 text-sm">
              <a
                href={`/api/meetings/${id}/summary-sheet.pdf`}
                className="font-semibold text-creek underline underline-offset-4"
              >
                Download summary PDF
              </a>
              <a
                href={data.links.packetPdf}
                className="font-semibold text-creek underline underline-offset-4"
              >
                Mirror packet PDF
              </a>
              {data.links.outcomesUi ? (
                <Link
                  to={data.links.outcomesUi}
                  className="font-semibold text-creek underline underline-offset-4"
                >
                  View outcomes
                </Link>
              ) : null}
              {data.meeting.minutesUrl ? (
                <SourceLink href={data.meeting.minutesUrl} label="Minutes" />
              ) : null}
              {data.meeting.videoUrl ? (
                <SourceLink href={data.meeting.videoUrl} label="Video" />
              ) : null}
            </div>
          </section>

          <section className="space-y-3">
            <h2 className="font-display text-2xl text-ink">Summary</h2>
            <p className="text-base leading-relaxed text-ink/80">{data.summary.body}</p>
            <p className="text-xs text-ink/45">
              Generated by AI ({data.summary.model}) — verify against primary minutes/video.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="font-display text-2xl text-ink">Per agenda item</h2>
            <ul className="space-y-4">
              {data.items.map((item) => (
                <li key={item.agendaItem.id} className="border-b border-ink/10 pb-4">
                  <p className="font-semibold text-ink">
                    {item.agendaItem.itemNumber}. {item.agendaItem.title}
                  </p>
                  {item.application ? (
                    <p className="mt-2 text-sm text-ink/70">
                      <Link
                        className="font-semibold text-creek underline"
                        to={item.application.caseBriefUi}
                      >
                        {item.application.caseNumber ?? item.application.id}
                      </Link>{' '}
                      · {item.application.projectType.replace(/_/g, ' ')} ·{' '}
                      {statusLabel(item.application.status)}
                      {item.structure ? (
                        <>
                          {' '}
                          ·{' '}
                          <Link
                            className="underline"
                            to={`/structures/${item.structure.publicSlug}`}
                          >
                            {item.structure.commonName ?? item.structure.addressLabel}
                          </Link>
                        </>
                      ) : null}
                    </p>
                  ) : item.note ? (
                    <p className="mt-2 text-sm text-ink/55">{item.note}</p>
                  ) : null}
                  {item.itemSummary ? (
                    <p className="mt-2 text-sm leading-relaxed text-ink/75">
                      {item.itemSummary.text}
                    </p>
                  ) : (
                    <p className="mt-2 text-sm text-ink/45">No per-item summary.</p>
                  )}
                </li>
              ))}
            </ul>
          </section>
        </div>
      ) : null}
    </div>
  );
}
